# Generated by Django 4.1 on 2024-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"verbose_name_plural": "Business"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name_plural": "Customer"},
        ),
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
