# Generated by Django 4.1 on 2024-03-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0004_pagevisit_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevisit",
            name="day_offset",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="pagevisit",
            unique_together={("path", "day_offset")},
        ),
    ]
