# Generated by Django 4.1 on 2024-03-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0005_pagevisit_day_offset_alter_pagevisit_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userauth",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
