# Generated by Django 4.1 on 2024-03-31 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0006_userauth_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("founded_date", models.DateField(verbose_name="Date Founded")),
                (
                    "founders",
                    models.CharField(
                        help_text="Comma-separated list of founders' names",
                        max_length=255,
                    ),
                ),
                (
                    "location",
                    models.CharField(help_text="Location of the farm", max_length=255),
                ),
                (
                    "number_of_employees",
                    models.IntegerField(
                        help_text="How many people work at the farm",
                        verbose_name="Number of Employees",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Farms",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="Drive.farm",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Events",
                "ordering": ["date"],
            },
        ),
    ]
