# Generated by Django 4.1 on 2024-03-31 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0007_farm_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Drive",
        ),
    ]
