# Generated by Django 4.1 on 2024-03-31 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0009_business_farm_product_farm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="business_id",
        ),
        migrations.AlterField(
            model_name="business",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="business_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Drive.business",
            ),
        ),
    ]
