# Generated by Django 4.1 on 2024-03-31 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0010_remove_business_business_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="business_name",
        ),
    ]
