# Generated by Django 4.1 on 2024-03-31 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0011_remove_product_business_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="business_name",
        ),
    ]
