# Generated by Django 4.1 on 2024-03-31 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0014_event_gallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["created_at"], "verbose_name_plural": "Events"},
        ),
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
    ]
