# Generated by Django 4.1 on 2024-03-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0015_alter_event_options_remove_event_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="gallery",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
