# Generated by Django 4.1 on 2024-03-31 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0016_farm_gallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="gallery",
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="profile_images/")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galleries",
                        to="Drive.event",
                    ),
                ),
            ],
        ),
    ]
