# Generated by Django 4.1 on 2024-03-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0017_remove_event_gallery_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="phonen",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
