# Generated by Django 4.1 on 2024-04-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0018_farm_email_farm_phonen"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="standard_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
