# Generated by Django 4.1 on 2024-04-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0019_product_standard_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
