# Generated by Django 4.1 on 2024-04-02 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0020_product_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
    ]
