# Generated by Django 4.1 on 2024-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0024_alter_cart_user_alter_event_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
