# Generated by Django 4.1 on 2024-04-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0025_product_url"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="volume",
            field=models.CharField(default=1, max_length=255),
        ),
    ]
