# Generated by Django 4.1 on 2024-04-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0027_coupon_cart_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
