# Generated by Django 4.1 on 2024-04-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0028_cart_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Drive.farm",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
