# Generated by Django 4.1 on 2024-04-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0030_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="founded_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date Founded"),
        ),
    ]
