# Generated by Django 4.1 on 2024-04-12 02:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0034_ordering_delete_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordering",
            name="order_status",
        ),
        migrations.RemoveField(
            model_name="ordering",
            name="price_at_purchase",
        ),
    ]
