# Generated by Django 4.1 on 2024-04-12 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0035_remove_ordering_order_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordering",
            name="email",
        ),
        migrations.RemoveField(
            model_name="ordering",
            name="fullname",
        ),
        migrations.RemoveField(
            model_name="ordering",
            name="phone",
        ),
    ]
