# Generated by Django 4.1 on 2024-04-12 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0036_remove_ordering_email_remove_ordering_fullname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordering",
            name="business",
        ),
    ]
