# Generated by Django 4.1 on 2024-04-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drive", "0037_remove_ordering_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordering",
            name="quantity",
            field=models.CharField(max_length=100),
        ),
    ]
